"""permission matrix and hospital role

Revision ID: 56a8e0eed1a8
Revises: a8c4ffbe90bd
Create Date: 2026-09-28 15:51:00.114135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = '56a8e0eed1a8'
down_revision: Union[str, None] = 'a8c4ffbe90bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###

    _seed_permission_matrix()


def _seed_permission_matrix() -> None:
    """Populate roles, permissions and their links.

    Idempotent, so re-running against a partially provisioned database is
    safe. The application also reconciles this on boot via
    ``ensure_permission_matrix``; the copy here exists so that
    ``alembic upgrade head`` alone is enough to provision a database.
    """
    from app.security.auth import ensure_permission_matrix

    session = Session(bind=op.get_bind())
    try:
        ensure_permission_matrix(session)
    finally:
        session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
