"""emergency session access token

Revision ID: b32e84ef129d
Revises: 56a8e0eed1a8
Create Date: 2026-09-28 16:02:21.336619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32e84ef129d'
down_revision: Union[str, None] = '56a8e0eed1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_sessions', sa.Column('access_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    # Sessions that predate this column were authorized by session id alone.
    # Retire them rather than grandfathering an unauthenticated read path;
    # they have a 30 minute life span, so nothing of value is lost.
    op.execute(
        "UPDATE emergency_sessions SET status = 'expired' "
        "WHERE access_token_hash IS NULL AND status = 'active'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergency_sessions', 'access_token_hash')
    # ### end Alembic commands ###
